### ISSUE TITLE
Convert website to Reactjs

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagirocks/HideandSeek#5]
Hello Contributors, I want someone to convert this vanilla website into React native or React.js

**Comment by shiblijamal10** [comment]
I can convert it

**Comment by arpittyagi102** [comment]
I have assigned you the issue @shiblijamal10

**Comment by arpittyagi102** [comment]
Hey @shiblijamal10, I am unassigning you from the issue

**Comment by Khareayushh** [comment]
Let me do it

**Comment by arpittyagi102** [comment]
Hey @Khareayushh, Sorry this issue should have been closed

**Comment by Khareayushh** [comment]
Notify me when you need some contribution related to frontend

**Comment by arpittyagi102** [comment]
there is a lot of scope for contribution in my other projects such as [LinkUp](https://github.com/arpittyagi102/linkup)

**Comment by Khareayushh** [comment]
great, thank you
