### ISSUE TITLE
Compress the media and images to improve the website's performance

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagirocks/HideandSeek#6]
Hello Contributers, I have noticed that the images used in this project makes the websites slower, also they load only when they are called, i want someone to compress the images and convert into webp format, and load the images as the website loads,
Ask me if you have any question...

**Comment by eKeiran** [comment]
hi I can help with this if you'd like!

**Comment by arpittyagi102** [comment]
hello @eKeiran, I have assigned you the issue
You may work on it now
